In [1]:
import pandas as pd
import pytz

In [2]:
#Loading the dataset
monthly_data = pd.read_csv('pedestrian-counting-system-monthly-counts-per-hour.csv')
monthly_data.head()

,Sensor_Name,SensingDateTime(Hour),LocationID,Direction_1,Direction_2,Total_of_Directions,Location
0,SprFli_T,2023-04-25T07:00:00+10:00,75,36,17,53,"-37.81515276, 144.97467661"
1,SprFli_T,2023-04-25T10:00:00+10:00,75,28,50,78,"-37.81515276, 144.97467661"
2,SprFli_T,2023-04-25T11:00:00+10:00,75,63,63,126,"-37.81515276, 144.97467661"
3,SprFli_T,2023-04-25T12:00:00+10:00,75,85,89,174,"-37.81515276, 144.97467661"
4,SprFli_T,2023-04-25T18:00:00+10:00,75,365,59,424,"-37.81515276, 144.97467661"

In [3]:
monthly_data['SensingDateTime(Hour)'] = pd.to_datetime(monthly_data['SensingDateTime(Hour)'])

In [4]:
# Define the start and end dates for filtering : Last 12 Months
start_date = pd.Timestamp('2023-04-01T00:00:00+10:00')
end_date = pd.Timestamp('2024-05-01T00:00:00+10:00')


pedisterian_data_year = monthly_data[(monthly_data['SensingDateTime(Hour)'] >= start_date) & (monthly_data['SensingDateTime(Hour)'] < end_date)]

In [5]:
# Dropping columns
pedisterian_data_year = pedisterian_data_year.drop(columns=['Direction_1','Direction_2'])

#Rename column names
pedisterian_data_year.head()

,Sensor_Name,SensingDateTime(Hour),LocationID,Total_of_Directions,Location
0,SprFli_T,2023-04-25 07:00:00+10:00,75,53,"-37.81515276, 144.97467661"
1,SprFli_T,2023-04-25 10:00:00+10:00,75,78,"-37.81515276, 144.97467661"
2,SprFli_T,2023-04-25 11:00:00+10:00,75,126,"-37.81515276, 144.97467661"
3,SprFli_T,2023-04-25 12:00:00+10:00,75,174,"-37.81515276, 144.97467661"
4,SprFli_T,2023-04-25 18:00:00+10:00,75,424,"-37.81515276, 144.97467661"

In [6]:
sensor_location = pd.read_csv('pedestrian-counting-system-sensor-locations.csv')

In [2]:
# Dropping redundant columns 
sensor_location = sensor_location.drop(columns=['Installation_Date','Note','Direction_1','Direction_2','Latitude','Longitude'])
sensor_location.head()

NameError: name 'sensor_location' is not defined

In [8]:
# Merging to get sensor location with Pedestrian counts
ped_count_year_sensor_location = pd.merge(sensor_location,pedisterian_data_year,left_on='Location_ID',right_on='LocationID',how="inner")
ped_count_year_sensor_location.head()

,Location_ID,Sensor_Description,Sensor_Name_x,Location_Type,Status,Location_x,Sensor_Name_y,SensingDateTime(Hour),LocationID,Total_of_Directions,Location_y
0,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,"-37.81380668, 144.96516718",Bou283_T,2023-04-26 07:00:00+10:00,2,170,"-37.81380668, 144.96516718"
1,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,"-37.81380668, 144.96516718",Bou283_T,2023-04-26 09:00:00+10:00,2,472,"-37.81380668, 144.96516718"
2,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,"-37.81380668, 144.96516718",Bou283_T,2023-04-26 11:00:00+10:00,2,1058,"-37.81380668, 144.96516718"
3,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,"-37.81380668, 144.96516718",Bou283_T,2023-04-26 17:00:00+10:00,2,1203,"-37.81380668, 144.96516718"
4,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,"-37.81380668, 144.96516718",Bou283_T,2023-04-26 19:00:00+10:00,2,398,"-37.81380668, 144.96516718"

In [9]:
ped_count_year_sensor_location = ped_count_year_sensor_location.drop(columns=['Location_x','Sensor_Name_y','LocationID'])

ped_count_year_sensor_location.head()

,Location_ID,Sensor_Description,Sensor_Name_x,Location_Type,Status,SensingDateTime(Hour),Total_of_Directions,Location_y
0,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 07:00:00+10:00,170,"-37.81380668, 144.96516718"
1,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 09:00:00+10:00,472,"-37.81380668, 144.96516718"
2,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 11:00:00+10:00,1058,"-37.81380668, 144.96516718"
3,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 17:00:00+10:00,1203,"-37.81380668, 144.96516718"
4,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 19:00:00+10:00,398,"-37.81380668, 144.96516718"

In [17]:
output ='SensorDataLTM.csv'
ped_count_year_sensor_location.to_csv(output,index = False)

In [13]:
buildings_data = pd.read_csv('landmarks-and-places-of-interest-including-schools-theatres-health-services-spor.csv')
buildings_data.head(25)

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Place of Worship,Church,St Francis Church,"-37.8118847831837, 144.962422614541"
1,Place of Worship,Church,St James Church,"-37.8101281201969, 144.952468571683"
2,Place of Worship,Church,St Mary's Anglican Church,"-37.8031663672997, 144.953761537074"
3,Place of Worship,Church,Scots Church,"-37.8145687802664, 144.96855105335"
4,Place of Worship,Church,St Michael's Uniting Church,"-37.8143851324913, 144.969174036096"
5,Place of Worship,Church,Greek Orthodox Church,"-37.8088064667555, 144.978259089269"
6,Place of Worship,Church,North Melbourne Uniting,"-37.8035538471344, 144.947671538375"
7,Place of Worship,Church,South Yarra Presbyterian Church,"-37.8407473645397, 144.98562699348"
8,Place of Worship,Synagogue,East Melbourne Synagogue,"-37.809113728917, 144.97422190954"
9,Transport,Transport Terminal,Port of Melbourne,"-37.8137384362671, 144.91753432375"
10,Leisure/Recreation,Major Sports & Recreation Facility,Carlton Football Club,"-37.7840864379557, 144.961967841559"
11,Education Centre,Primary Schools,Carlton Gardens Primary School,"-37.8020953835112, 144.969406272035"
12,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens North,"-37.8017690847403, 144.971997551189"
13,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Kings Domain,"-37.8255239795833, 144.974107925144"
14,Education Centre,Secondary Schools,Melbourne Grammar School,"-37.8342561018747, 144.976285045233"
15,Place Of Assembly,Theatre Live,FairFax Studio,"-37.8216684581887, 144.968836241692"
16,Leisure/Recreation,Major Sports & Recreation Facility,Flemington Racecourse,"-37.7908082646624, 144.912142987372"
17,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Treasury Gardens,"-37.8143993575938, 144.975952335785"
18,Mixed Use,Retail/Office,Treasury Reserve,"-37.8129178793082, 144.975236759799"
19,Health Services,Private Hospital,Epworth Freemasons Hospital : Medical Centre,"-37.8093444587231, 144.982336768182"
20,Community Use,Government Building,Melbourne Magistrates Court,"-37.8136147671606, 144.956846193891"
21,Transport,Railway Station,Flagstaff Railway Station,"-37.8122356514626, 144.956318211113"
22,Leisure/Recreation,Major Sports & Recreation Facility,Melbourne Cricket Ground (MCG),"-37.8194921618419, 144.983402879078"
23,Vacant Land,Vacant Land - Undeveloped Site,Melbourne International Karting Complex,"-37.8310746380616, 144.913822928701"
24,Mixed Use,Retail/Office/Carpark,Southgate Arts and Leisure Precinct,"-37.8202245786597, 144.965989052839"

In [26]:
buildings_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Theme         242 non-null    object
 1   Sub Theme     242 non-null    object
 2   Feature Name  242 non-null    object
 3   Co-ordinates  242 non-null    object
dtypes: object(4)
memory usage: 7.7+ KB

In [13]:
# Define the start and end dates for filtering : Last 12 Months
start_date1 = pd.Timestamp('2023-10-01T00:00:00+10:00')
end_date1 = pd.Timestamp('2023-11-01T00:00:00+10:00')


pedisterian_data_year_oct = ped_count_year_sensor_location[(ped_count_year_sensor_location['SensingDateTime(Hour)'] >= start_date) & (ped_count_year_sensor_location['SensingDateTime(Hour)'] < end_date)]

In [14]:
pedisterian_data_year_oct.head()

,Location_ID,Sensor_Description,Sensor_Name_x,Location_Type,Status,SensingDateTime(Hour),Total_of_Directions,Location_y
0,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 07:00:00+10:00,170,"-37.81380668, 144.96516718"
1,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 09:00:00+10:00,472,"-37.81380668, 144.96516718"
2,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 11:00:00+10:00,1058,"-37.81380668, 144.96516718"
3,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 17:00:00+10:00,1203,"-37.81380668, 144.96516718"
4,2,Bourke Street Mall (South),Bou283_T,Outdoor,A,2023-04-26 19:00:00+10:00,398,"-37.81380668, 144.96516718"

In [18]:
o ='SensorDataOct.csv'
pedisterian_data_year_oct.to_csv(o,index = False)

In [ ]:
# Group by Date and Status, then count the number of occurrences
status_trend = df.groupby(['Date', 'Status']).size().unstack(fill_value=0)

import matplotlib.pyplot as plt

# Plotting the trend of active vs inactive sensors over time
plt.figure(figsize=(12, 6))
status_trend.plot(kind='line', ax=plt.gca())
plt.title('Trend of Active vs Inactive Sensors Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Sensors')
plt.legend(title='Status')
plt.grid(True)
plt.tight_layout()
plt.show()